import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ReportView } from "@/components/ReportView";
import { generateVisibilityReport } from "@/lib/reporting/generateVisibilityReport";
import { generateMarkdownReport } from "@/lib/reporting/generateMarkdownReport";
import { generateFixPack } from "@/lib/reporting/generateFixPack";
import { integrityHomeExteriorsAudit } from "@/lib/reporting/sampleAudit";
import type { RawAuditJson } from "@/lib/reporting/types";

export const dynamic = "force-dynamic";
export const metadata = {
  title: "Report Preview · GeoViz",
  description:
    "Internal preview of the report generator output.",
  robots: { index: false, follow: false },
};

type SearchParams = {
  url?: string;
  business?: string;
  orderId?: string;
};

export default function ReportPreviewPage({
  searchParams,
}: {
  searchParams?: SearchParams;
}) {
  const isTestRender = Boolean(
    searchParams?.url || searchParams?.business || searchParams?.orderId,
  );

  const audit: RawAuditJson = isTestRender
    ? {
        ...integrityHomeExteriorsAudit,
        url: searchParams?.url ?? integrityHomeExteriorsAudit.url,
        businessName:
          searchParams?.business ?? integrityHomeExteriorsAudit.businessName,
      }
    : integrityHomeExteriorsAudit;

  const report = generateVisibilityReport(audit);
  const markdown = generateMarkdownReport(report, { includeDebug: true });
  const fixPack = generateFixPack(report);

  return (
    <main>
      <Header />

      <section className="border-b border-white/5">
        <div className="container-page py-12">
          {isTestRender ? (
            <div className="mb-5 rounded-md border border-amber-300/30 bg-amber-300/10 px-4 py-3 text-sm text-amber-100">
              <strong className="font-semibold">Test render.</strong> This
              report was generated from the local test bypass — Stripe was
              skipped. The technical findings come from the Integrity sample
              audit, but the business name and URL below are yours.
              {searchParams?.orderId ? (
                <>
                  {" "}
                  Order id:{" "}
                  <code className="text-amber-200">{searchParams.orderId}</code>
                </>
              ) : null}
            </div>
          ) : null}

          <p className="pill">Internal · Report generator preview</p>
          <h1 className="h2 mt-3">Report Preview — {report.businessName}</h1>
          {report.websiteUrl ? (
            <p className="muted mt-2 text-sm break-all">{report.websiteUrl}</p>
          ) : null}
          <p className="muted mt-3 max-w-2xl text-sm">
            Renders the output of <code>generateVisibilityReport()</code>. Use
            this page during fulfillment to verify the generator before sending
            the report to a customer.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link href="/sample-report" className="btn-ghost">
              View as customer-facing sample
            </Link>
            <Link href="/" className="btn-ghost">
              Home
            </Link>
          </div>
        </div>
      </section>

      <section>
        <div className="container-page py-12">
          <ReportView report={report} />
        </div>
      </section>

      <section className="border-t border-white/5">
        <div className="container-page py-12">
          <p className="section-eyebrow">Markdown export</p>
          <h2 className="h3 mt-2">
            Copy this into Gmail, Google Docs, or your PDF tool.
          </h2>
          <p className="muted mt-2 text-sm">
            Generated by <code>generateMarkdownReport()</code>.
          </p>
          <pre className="mt-6 max-h-[600px] overflow-auto rounded-lg border border-white/10 bg-ink-900/80 p-6 text-xs leading-relaxed text-white/85">
{markdown}
          </pre>
        </div>
      </section>

      <section className="border-t border-white/5">
        <div className="container-page py-12">
          <p className="section-eyebrow">Fix Pack — customer deliverable</p>
          <h2 className="h3 mt-2">
            The AI Visibility Foundation Fix template, prefilled.
          </h2>
          <p className="muted mt-2 text-sm">
            Generated by <code>generateFixPack()</code>. Business name, score,
            and top issue are auto-filled. Bracketed placeholders
            (<code>[SERVICE]</code>, <code>[CITY/REGION]</code>, schema
            address/phone, etc.) are filled by the consultant during
            fulfillment.
          </p>
          <pre className="mt-6 max-h-[700px] overflow-auto rounded-lg border border-accent/30 bg-ink-900/80 p-6 text-xs leading-relaxed text-white/85">
{fixPack}
          </pre>
        </div>
      </section>

      <Footer />
    </main>
  );
}
